# Generated by Django 6.0.2 on 2026-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking_accounts", "0003_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(default="Savings", max_length=50),
            preserve_default=False,
        ),
    ]
